# First steps with `numpy`

Python by itself is a rather slow language. Taking the performance of the compiled C language as unit one, you can get an idea of its performance, e.g., from the [benchmark game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/python3-gcc.html). This is partly due to the fact that Python is interpreted and not compiled. But even among the interpreter languages, Python is slow. 

Then why is Python so popular in data science and how can we implement computation-heavy algorithms efficiently in Python? The second question can be answered more easily that the first. Python has a light-weight interface to C so that computation-heavy routines can simply be written in C and then used conveniently from Python. The first question probably has many answers, two of which certainly are that Python has:
* an extraordinary beautiful syntax allowing to quickly lay out the outer loops of algorithms;
* a large ecosystems of additional packages either to do the heavy lifting in the inner loops, often exploiting multi CPU/GPU processing without much overhead, or help to obtain, pre-process, inspect, and visualize data.

In our course, we want to focus on the implementation of the algorithms and not on the performance. Nevertheless, we will need some basic performance in numerical functions and operations. For this we will use the standard `numpy` package, which allows to do linear algebra efficiently in Python. 

In [1]:
import numpy as np

The basic object of `numpy` is the Numpy Array that can be created conveniently using a Python `list`.

In [3]:
M = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
type(M)

numpy.ndarray

In [5]:
print(M)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
M.shape

(3, 2)

This is the numerical equivalent of a $\mathbb R^{3\times 2}$ matrix. But we can also create tensors of any dimension, here creating a $\mathbb R^{4\times 3\times 2}$ using our previously defined matrix $M$ and several operations and functions that operate on the individual coefficients (which is Numpy's way of allowing to vectorize operations and functions efficiently on even large arrays without the need of invoking any slow Python loop):

In [8]:
T = np.array([M, 2*M, np.exp(M), np.sin(4*M)])
print(T)
print('The tensor T has the dimensions: ', T.shape)

[[[ 1.00000000e+00  2.00000000e+00]
  [ 3.00000000e+00  4.00000000e+00]
  [ 5.00000000e+00  6.00000000e+00]]

 [[ 2.00000000e+00  4.00000000e+00]
  [ 6.00000000e+00  8.00000000e+00]
  [ 1.00000000e+01  1.20000000e+01]]

 [[ 2.71828183e+00  7.38905610e+00]
  [ 2.00855369e+01  5.45981500e+01]
  [ 1.48413159e+02  4.03428793e+02]]

 [[-7.56802495e-01  9.89358247e-01]
  [-5.36572918e-01 -2.87903317e-01]
  [ 9.12945251e-01 -9.05578362e-01]]]
The tensor T has the dimensions:  (4, 3, 2)


Such Numpy Arrays can be created using different routines:

In [9]:
Z = np.zeros((3,2))
print(Z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
O = np.ones((3,2))
print(O)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
D = np.diag((1,2,3,4))
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Ranges:

In [12]:
R = np.arange(7, 23, 2)
print(R)

[ 7  9 11 13 15 17 19 21]


In [13]:
L = np.linspace(0, np.pi, 10)
print(L)

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


Random numbers uniformly distributed:

In [14]:
A = np.random.rand(3, 2)
print(A)

[[0.78012854 0.99363996]
 [0.95742196 0.75055996]
 [0.15176901 0.78186039]]


or according the normal distribution:

In [18]:
B = np.random.normal(size=(3, 2))
print(B)

[[ 0.18462626  0.47807632]
 [-1.18175921  2.37674629]
 [ 0.90145998  0.22085449]]


Arrays can be conveniently indexed keeping in mind that Numpy counts starting from 0:

In [20]:
print(f'The (1,2) coefficient of the matrix {M} equals {M[0,1]}')

The (1,2) coefficient of the matrix [[1 2]
 [3 4]
 [5 6]] equals 2


and sliced as follows. For example, the sub-matrix containing the coefficients of the 1st column of 2nd and 3rd row are obtained by:

In [21]:
print(M[1:3,0])

[3 5]


The sub-matrix of the coefficients of the entire 2nd and 3rd row are given by:

In [22]:
print(M[1:3,:])

[[3 4]
 [5 6]]


Negative indices count backwards from the end. The second element is the second last row:

In [23]:
print(M[-2])

[3 4]


and the last element of the second last row:

In [24]:
print(M[-2,-1])

4


Numpy offers many quick manupulations such as reshaping, stacking, and appending:

In [19]:
print(np.reshape(M, (2, 3)))

[[1 2 3]
 [4 5 6]]


In [25]:
print(np.hstack((M, 2*M)))

[[ 1  2  2  4]
 [ 3  4  6  8]
 [ 5  6 10 12]]


In [26]:
print(np.vstack((M, 2*M)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 2  4]
 [ 6  8]
 [10 12]]


The same can be achieved by appending:

In [30]:
print(np.append(M, 2*M, axis=0))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 2  4]
 [ 6  8]
 [10 12]]


Broadcasting mechanism in vectorized operations:

In [31]:
v = np.array([[7, 8]])
print(f'Multiplying\n\n{M}\n\nby\n\n{v}\n\ngives\n\n{M * v}')

Multiplying

[[1 2]
 [3 4]
 [5 6]]

by

[[7 8]]

gives

[[ 7 16]
 [21 32]
 [35 48]]


because internally Numpy broadcasts the row vector $v$ to the matrix $\begin{pmatrix} 7 & 8\\ 7 & 8\\ 7 & 8\end{pmatrix}$ and then carries out the multiplication per coefficient. The broadcasting will be done automatically whenever the dimensions allow. In the next example, Numpy broadcasts automatically along the other axis:

Note that $v$ is a 1x2 matrix or row vector. It can be transposed using:

In [32]:
v.T

array([[7],
       [8]])

In [33]:
w = np.array([[7], [8], [9]])
print(M + w)

[[ 8  9]
 [11 12]
 [14 15]]


Matrix multiplication, contrary to coefficient-wise multiplication, can be carrying out as follows using the `@` operator:

In [34]:
print(M @ v.T)

[[23]
 [53]
 [83]]


There are many functions to infer aggregated information about arrays such as:

In [35]:
np.mean(R)

14.0

In [36]:
np.sum(R)

112

In [37]:
np.max(R)

21

In [38]:
l = A.flatten()
i = np.argmax(l)
print(f'The largest coefficient of list {l} is at index {i} and has the value {l[i]}')

The largest coefficient of list [0.78012854 0.99363996 0.95742196 0.75055996 0.15176901 0.78186039] is at index 1 and has the value 0.9936399639372515


There are some ready made linear algebra functions:

In [45]:
print(np.linalg.norm(v))
print(np.sqrt(np.dot(v, v.T)))

10.63014581273465
[[10.63014581]]


For matrix multiplication I often tend to use the `@` operator:

In [47]:
print(np.sqrt(v @ v.T))

[[10.63014581]]


In [43]:
print(f'The result of `v.T @ v` should be a {v.T.shape[0]}x{v.shape[1]} matrix:')
print(v.T @ v)
print(f'\nand the one of `v @ v.T` a {v.shape[0]}x{v.T.shape[1]} matrix:')
print(v @ v.T)

The result of `v.T @ v` should be a 2x2 matrix:
[[49 56]
 [56 64]]

and the one of `v @ v.T` a 1x1 matrix:
[[113]]


Note that the result is a 1x1 matrix. In case needed, as any other tensor, it can be flattened by:

In [42]:
r = v @ v.T
print(f'The value of `v @ v.T`: {r}')
print(f'As scalar: {r.item()}')
print(f'Flattened: {r.flatten()}')

The value of `v @ v.T`: [[113]]
As scalar: 113
Flattened: [113]
